/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "DateiTransfer_constants.h"



const DateiTransferConstants g_DateiTransfer_constants;

DateiTransferConstants::DateiTransferConstants() {
}



