/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DateiTransfer_CONSTANTS_H
#define DateiTransfer_CONSTANTS_H

#include "DateiTransfer_types.h"



class DateiTransferConstants {
 public:
  DateiTransferConstants();

};

extern const DateiTransferConstants g_DateiTransfer_constants;



#endif
